# Inference-only deployment: db + inference + proxy
# Usage: docker compose -f compose-inference.yaml up -d
#
# This is for the "batch-train, then serve" pattern where:
#   1. You run the full stack to train models and create API keys
#   2. You deploy only the inference server for production serving
#
# See docs/guides/standalone-inference.md for the full guide.

services:
  db:
    image: postgres:17.2-alpine
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "recotem_user", "-d", "recotem"]
      interval: "5s"
      timeout: "3s"
      retries: 5
      start_period: "5s"
    env_file:
      - envs/production.env
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - backend-net

  inference:
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    build:
      context: ./inference
      dockerfile: Dockerfile
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/health || exit 1"]
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 5
    volumes:
      - data-location:/data:ro
    env_file:
      - envs/production.env
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 512M
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"
    networks:
      - backend-net

  proxy:
    depends_on:
      inference:
        condition: service_healthy
    restart: unless-stopped
    image: nginx:1.27.3-alpine
    ports:
      - "8000:8000"
    volumes:
      - ./nginx-inference.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - backend-net

volumes:
  data-location:
  db-data:

networks:
  backend-net:
    driver: bridge
