services:
  queue:
    image: rabbitmq:4.0
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: "5s"
      timeout: "3s"
      retries: 5
      start_period: "5s"
    env_file:
      - envs/dev.env
  db:
    image: postgres:14
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "recotem_user", "-d", "recotem"]
      interval: "5s"
      timeout: "3s"
      retries: 5
      start_period: "5s"
    env_file:
      - envs/dev.env
  backend:
    depends_on:
      db:
        condition: service_healthy
      queue:
        condition: service_healthy
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        - RECOTEM_DEV=true
    volumes:
      - ./backend/recotem:/app
      - data-location:/app/data
    ports:
      - "8000:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/api/ping/ || exit 1"]
      interval: "10s"
      timeout: "5s"
      retries: 2
      start_period: "5s"
    env_file:
      - envs/dev.env
  celery_worker:
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_healthy
      queue:
        condition: service_healthy
    build:
      context: ./backend
      dockerfile: celery.dockerfile
    volumes:
      - ./backend/recotem:/app
      - data-location:/app/data
    env_file:
      - envs/dev.env
volumes:
  data-location:
  db-data:
