services:
  queue:
    image: rabbitmq:4.0
    env_file:
      - envs/dev.env
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: "5s"
      timeout: "3s"
      retries: 5
      start_period: "5s"
  backend:
    depends_on:
      queue:
        condition: service_healthy
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        - RECOTEM_TESTING=true
    volumes:
      - ./backend/recotem:/app
      - test-data-location:/app/data/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:80"
    environment:
      - DJANGO_SETTINGS_MODULE=recotem.settings
      - CELERY_BROKER_URL=amqp://user:bitnami@queue:5672
      - RECOTEM_TESTING=true
    stdin_open: true # docker run -i
    tty: true # docker run -t
    command: >
      sh -c '
        if ! pytest -s --cov=./recotem/ --cov-report=html tests/; then
          echo "test failed"
          exit 1;
        fi
        coverage xml
        rm -rf data/training_data
        rm -rf data/models
      '
volumes:
  test-data-location:
