# CI-specific Docker Compose override
# Usage: docker compose -f compose.yaml -f compose.ci.yaml up -d
services:
  backend:
    healthcheck:
      start_period: 120s
      interval: 10s
      retries: 12
    environment:
      - SECRET_KEY=${SECRET_KEY:-ci-test-secret-key-for-testing-only-not-production}
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD}
      - DEBUG=true
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - THROTTLE_ANON_RATE=1000/min
      - THROTTLE_USER_RATE=1000/min
      - THROTTLE_LOGIN_RATE=1000/min
      - THROTTLE_RECOMMENDATION_RATE=1000/min
  worker:
    environment:
      - SECRET_KEY=${SECRET_KEY:-ci-test-secret-key-for-testing-only-not-production}
      - DEBUG=true
  proxy:
    volumes:
      - ./nginx.ci.conf:/etc/nginx/conf.d/default.conf:ro
