services:
  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "recotem_user", "-d", "recotem"]
      interval: "5s"
      timeout: "3s"
      retries: 5
      start_period: "5s"
    env_file:
      - envs/dev.env

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "if [ -n \"$REDIS_PASSWORD\" ]; then redis-cli -a \"$REDIS_PASSWORD\" ping; else redis-cli ping; fi",
        ]
      interval: "5s"
      timeout: "3s"
      retries: 5
      start_period: "5s"

volumes:
  dev-db-data:
