# Production Docker Compose configuration
# Usage:
#   1. Copy .env.example to .env and configure the values
#   2. docker compose -f compose-production.yaml up -d
#
# This configuration uses pre-built images from GHCR.
# For building from source, use compose.yaml instead.

services:
  queue:
    image: rabbitmq:4.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  backend:
    image: ghcr.io/tohtsky/recotem/backend:latest
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      queue:
        condition: service_healthy
    volumes:
      - data-location:/app/data
      - static-files:/app/dist/static
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - CELERY_BROKER_URL=amqp://guest:guest@queue:5672
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=false
    healthcheck:
      test: curl -f http://localhost:80/api/ping/ || exit 1
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 3

  celery_worker:
    image: ghcr.io/tohtsky/recotem/celery:latest
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - data-location:/app/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - CELERY_BROKER_URL=amqp://guest:guest@queue:5672

  frontend:
    image: ghcr.io/tohtsky/recotem/frontend:latest
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy

  proxy:
    image: nginx:1.27.3
    restart: unless-stopped
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_healthy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static-files:/app/dist/static:ro
    ports:
      - "${PORT:-80}:80"

volumes:
  data-location:
  db-data:
  static-files:
