version: "3.7"
services:
  queue:
    image: rabbitmq:3
    ports:
      - "5672:5672"
  db:
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - envs/production.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    volumes:
      - data-location:/app/data
    ports:
      - "8000:80"
    env_file:
      - envs/production.env
  celery_worker:
    build:
      context: ./backend
      dockerfile: celery.dockerfile
    volumes:
      - data-location:/app/data
    env_file:
      - envs/production.env
volumes:
  data-location:
    driver: local
  db-data:
    driver: local
