version: "3.7"
services:
  queue:
    image: bitnami/rabbitmq:3.9
  db:
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - envs/production.env
  backend:
    depends_on:
      - db
      - queue
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    volumes:
      - data-location:/app/data
      - static-files:/app/dist/static
    healthcheck:
      test: curl -f http://localhost:80/api/ping/ || exit 1
      interval: 5s
      timeout: 5s
      start_period: 20s
      retries: 10
    env_file:
      - envs/production.env
  celery_worker:
    depends_on:
      backend:
        condition: service_healthy
    build:
      context: ./backend
      dockerfile: celery.dockerfile
    volumes:
      - data-location:/app/data
    env_file:
      - envs/production.env
  frontend:
    depends_on:
      backend:
        condition: service_healthy
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    env_file:
      - envs/production.env
  proxy:
    depends_on:
      - frontend
    image: nginx:1.21.1
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static-files:/app/dist/static
    ports:
      - "8000:80"
volumes:
  data-location:
    driver: local
  db-data:
    driver: local
  static-files:
    driver: local
