version: "3.3"
services:
  #  queue:
  #    image: rabbitmq:3
  #    ports:
  #      - "5673:5672"
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    volumes:
      - data-location:/app/data
    ports:
      - "8000:80"
    environment:
      - DEBUG=on
volumes:
  data-location:
    driver: local
