version: "3.7"
services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    env_file:
      - envs/dev.env
    volumes:
      - data-location:/data/
    command: server /data
  queue:
    image: rabbitmq:3
  db:
    image: postgres:12
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - envs/production.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
  backend:
    depends_on:
      - db
      - queue
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    volumes:
      - data-location:/app/data
      - static-files:/app/dist/static
    env_file:
      - envs/production.env
  celery_worker:
    depends_on:
      - backend
    build:
      context: ./backend
      dockerfile: celery.dockerfile
    volumes:
      - data-location:/app/data
    env_file:
      - envs/production.env
  proxy:
    depends_on:
      - backend
      - frontend
    build:
      context: .
      dockerfile: proxy.dockerfile
    volumes:
      - static-files:/app/dist/static
    ports:
      - "8000:80"
volumes:
  data-location:
    driver: local
  db-data:
    driver: local
  static-files:
    driver: local
