version: "3.3"
services:
  queue:
    image: rabbitmq:3
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    volumes:
      - data-location:/app/data
    ports:
      - "8000:80"
    environment:
      - DEBUG=on
  celery_worker:
    build:
      context: ./backend
      dockerfile: celery.dockerfile
    volumes:
      - data-location:/app/data
    environment:
      - DEBUG=on
      - CELERY_BROKER_URL=amqp://guest@queue:5672
volumes:
  data-location:
    driver: local
