# Generated by Django 3.2 on 2021-06-05 13:32

import functools

import django.db.models.deletion
from django.db import migrations, models

import recotem.api.models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametertuningjob",
            name="irspack_version",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="parametertuningjob",
            name="train_after_tuning",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trainedmodel",
            name="irspack_version",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="parametertuningjob",
            name="tuned_model",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.trainedmodel",
            ),
        ),
        migrations.AlterField(
            model_name="trainingdata",
            name="upload_path",
            field=models.FileField(
                upload_to=functools.partial(
                    recotem.api.models.upload_to, *("training_data",), **{}
                )
            ),
        ),
    ]
