"""The distributions must contain the files the documentation tells you to run.

`[tool.hatch.build.targets.sdist] include` used to read
``["src/recotem", "README.md", "LICENSE"]``.  Hatchling's include patterns are
gitignore-style, so an unanchored ``README.md`` matches a ``README.md`` at ANY
depth: the sdist shipped ``docs/README.md`` and all nine
``examples/*/README.md`` -- and, because no pattern named ``examples``, none of
the ``recipe.yaml``, CSV, or manifest files those READMEs instruct the reader
to run.  Nine example directories consisting only of instructions for files
that were not in the archive.

The wheel never shipped ``examples/`` and deliberately still does not: a wheel
unpacks into ``site-packages``, where an ``examples/`` directory would be
neither findable by a relative path nor cleanly removable on uninstall.  Lean
wheel, complete sdist.

**Scope boundary.** This file owns the *distributions* -- what
``pyproject.toml``'s build targets put in the sdist, and whether a file a
shipped document tells you to run is actually there.  It asserts nothing about
``docs/getting-started.md``'s Path B, which is owned by
``tests/unit/test_getting_started_path_b.py`` (`#262`): that PR rewrites Path B
to run from a bare ``pip install`` with no checkout, so the two surfaces are
disjoint by construction -- Path B stops naming ``examples/`` at all, and this
file keeps watching every *other* document that does.  The boundary is written
down because a surface half-owned by two guards is how a surface ends up
unowned.

Both guards read whole files and fail when they match nothing, so a rename or
a reworded section cannot silently switch them off -- the failure mode `#220`
hit when a regex quietly stopped matching.
"""

from __future__ import annotations

import re
import tomllib
from pathlib import Path

_ROOT = Path(__file__).resolve().parents[2]

# An example path the reader is told to RUN: the argument of a `recotem`
# subcommand or of `python`, inside a fenced block.  Requires a file component,
# so bare directory mentions ("see examples/k8s") are not treated as file
# claims, and requires the command, because prose legitimately names paths that
# are not files in this repository -- `examples/sql-sqlite/events.db` is generated by `seed.py`
# at step time, and `examples/mind/mind_small_feature_aware_ials.py` in
# recipe-reference.md is a path inside *irspack's* tree, cited for provenance.
# Neither breaks a reader; a `recotem train examples/…` that is not there does.
_RUN_EXAMPLE = re.compile(
    r"(?:recotem\s+(?:train|serve|validate|inspect)\b[^\n]*?|python\s+)"
    r"(?P<path>examples/[A-Za-z0-9._-]+(?:/[A-Za-z0-9._-]+)+)"
)

_FENCE = re.compile(r"^```[^\n]*\n(.*?)^```", re.MULTILINE | re.DOTALL)


def _code_blocks(text: str) -> list[tuple[int, str]]:
    """Return ``(offset, body)`` for every fenced block in *text*."""
    return [(m.start(1), m.group(1)) for m in _FENCE.finditer(text)]


def _prose_files() -> list[Path]:
    files = [_ROOT / name for name in ("README.md", "CLAUDE.md")]
    files.extend(sorted((_ROOT / "docs").rglob("*.md")))
    return [f for f in files if f.is_file()]


def test_sdist_include_patterns_are_anchored_and_cover_examples() -> None:
    """Anchored patterns only, and ``examples`` named explicitly.

    A leading ``/`` is what stops ``README.md`` from matching nine nested
    READMEs.  Reverting the include list to its unanchored form fails here.
    """
    config = tomllib.loads((_ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    include = config["tool"]["hatch"]["build"]["targets"]["sdist"]["include"]

    assert include, (
        "[tool.hatch.build.targets.sdist] include is empty -- this guard is "
        "watching nothing."
    )

    unanchored = [p for p in include if not p.startswith("/")]
    assert not unanchored, (
        "these sdist include patterns are unanchored, so hatchling matches "
        f"them at every depth, not just the repository root: {unanchored}. "
        "Prefix each with '/'. An unanchored 'README.md' is what pulled "
        "docs/README.md and nine examples/*/README.md into the sdist while "
        "shipping none of the files those READMEs describe."
    )

    assert "/examples" in include, (
        "the sdist does not ship examples/. Every examples/*/README.md "
        "instructs the reader to run files from that directory, and the "
        "unanchored include pattern shipped those READMEs; shipping them "
        "without the recipes is worse than shipping neither."
    )


def test_every_example_file_a_doc_tells_you_to_run_exists() -> None:
    """A doc that says ``recotem train examples/x/y`` must ship ``examples/x/y``."""
    missing: list[str] = []
    checked = 0
    for path in _prose_files():
        text = path.read_text(encoding="utf-8")
        for offset, block in _code_blocks(text):
            for match in _RUN_EXAMPLE.finditer(block):
                ref = match.group("path")
                checked += 1
                if not (_ROOT / ref).exists():
                    lineno = text.count("\n", 0, offset + match.start("path")) + 1
                    missing.append(f"{path.relative_to(_ROOT)}:{lineno}: {ref}")

    assert checked, (
        "no shipped prose file runs a recotem or python command against an "
        "examples/<dir>/<file> path -- the regex has stopped matching and "
        "this guard is watching nothing."
    )
    assert not missing, (
        "shipped prose points at example files that do not exist in the "
        "repository:\n  " + "\n  ".join(sorted(set(missing)))
    )
