name: build-image
on:
  push:
    branches:
      - 'build-image-gha'
jobs:
  build-backend-worker:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image (backend)
        run: |
          tag=ghcr.io/codelibs/recotem-backend:${GITHUB_REF##*/}
          cd backend && \
            docker buildx build -f backend.dockerfile -t "${tag}" \
              --push --platform linux/amd64,linux/arm64 .
          cd ..
      - name: Build and push docker image (worker)
        run: |
          tag=ghcr.io/codelibs/recotem-worker:${GITHUB_REF##*/}
          cd backend && \
            docker buildx build -f celery.dockerfile -t "${tag}" \
              --push --platform linux/amd64,linux/arm64 .
          cd ..

  build-frontend:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image (frontend)
        run: |
          tag=ghcr.io/codelibs/recotem-frontend:${GITHUB_REF##*/}
          cd frontend && \
            docker buildx build -f frontend.dockerfile -t "${tag}" \
             --push --platform linux/amd64,linux/arm64 .
